### PR TITLE
fix deprecations

### PR DESCRIPTION
**Pull request by SuperFola**
- adding vcpkg include dirs to vscode
- adding virtual destructors
- migrating from TCODColor to tcod::ColorRGB where possible

### CODE REVIEW

**Comment by SuperFola** [comment]
Hey @HexDecimal, I'm wondering why utf8proc is blocking builds, isn't it already included in libtcod?

**Comment by HexDecimal** [comment]
When built from Vcpkg libtcod gets libraries from Vcpkg instead of using its vendored sources. Can you try the latest Vcpkg ports?  Pull from master on the vcpkg submodule.

**Comment by SuperFola** [comment]
It seems like I am already on master in the vcpkg submodule.
The vendor vs vcpkg source explains it. Maybe a solution would be to add utf8proc as a dependency in the vcpkg.json file on this repo?

**Comment by HexDecimal** [comment]
The workflow logs show that `utf8proc` was built by Vcpkg, and the link flag shows that it knows it has to link it, so something is interfering with linking somehow.

**Comment by HexDecimal** [comment]
The submodule points to HexDecimal/vcpkg not vcpkg/vcpkg, so you don't have the latest ports here.

**Comment by HexDecimal** [comment]
Switch to microsoft/vcpkg then pull from master and try again.  I think this error is from an outdated port of libtcod which didn't have utf8proc in its CMake config file.

**Comment by SuperFola** [comment]
Oh my bad, I'm trying this now.

As a bad fix, one can add utf8proc, find the unofficial-utf8proc package and link against utf8proc. However this is weird because upon inspecting the build folder and the artifacts generated, there is a lib8utfproc which cmake should know about, in a lib folder.

**Comment by HexDecimal** [comment]
You're welcome.  I've mostly been distracted trying to refactor really old badly designed libtcod projects.

**Pull request merged**
